version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    environment:
      - MYSQL_DATABASE=badnotes
      - MYSQL_USER=baduser
      - MYSQL_PASSWORD=foobarbaz
      - MYSQL_HOST=db
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - db
    links:
      - php
  php:
    image: php:8.0.1-fpm
    volumes:
      - .:/var/www/html
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=badnotes
      - MYSQL_USER=baduser
      - MYSQL_ROOT_PASSWORD=foobarbaz
      - MYSQL_PASSWORD=foobarbaz
    volumes:
      - db_data:/var/lib/mysql
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data: { driver: local }